# Generated by Django 3.2 on 2022-11-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstudent',
            name='code_number',
        ),
    ]
