# Generated by Django 3.2 on 2022-11-12 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20221112_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstudent',
            name='adminschool_fees',
        ),
        migrations.AddField(
            model_name='formstudent',
            name='school_fees',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
