# Generated by Django 3.2 on 2022-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20221112_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstudent',
            name='adminschool_fees',
        ),
        migrations.AlterField(
            model_name='formstudent',
            name='school_fees',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Standardfees',
        ),
    ]
