# Generated by Django 3.2 on 2022-11-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20221112_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formstudent',
            options={'managed': True, 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelTable(
            name='formstudent',
            table='Formstudent',
        ),
    ]
